
name: ped-arm-cnn
channels:
          - conda-forge
          - pytorch
          - nvidia
dependencies:
          - python=3.9.10
          - pytorch=1.12.1
          - torchvision=0.13.1
          - cudatoolkit=11.3
          - numpy=1.23.3
          - matplotlib=3.6.1
          - pillow=9.2.0
          - pandas=1.5.0
          - scikit-image=0.19.3
          - scikit-learn=1.1.2
          - opencv
          - albumentations
          - jupyterlab=3.4.8
          - nb_conda_kernels=2.3.1
